- name: Install Debain Database
  import_tasks: db_Debian.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Install RedHat Database
  import_tasks: db_RedHat.yaml
  when: ansible_facts['os_family'] == "RedHat"
